### ISSUE TITLE
Install casks task referencing item name

### ISSUE THREAD

**Issue by chadbean** [ravenac95/readytowork#1]
When trying to run `make work`, I would receive this error:

> fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'name'\n\nThe error appears to have been in '/Users/chad/Projects/readytowork/roles/casks/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install casks\n  ^ here\n"}

I logged (debug) the `installed_apps.results` registered var, and it looked something like the following:

> "msg": "[{u'stat': {u'uid': 502, u'exists': True, u'woth': False, u'mtime': 1473811971.0, u'inode': 678695, u'isgid': False, u'size': 102, u'wgrp': False, u'isuid': False, u'isreg': False, u'pw_name': u'chad', u'gid': 80, u'ischr': False, u'wusr': True, u'xoth': True, u'rusr': True, u'nlink': 3, u'issock': False, u'rgrp': True, u'gr_name': u'admin', u'path': u'/Applications/Google Chrome.app', u'xusr': True, u'atime': 1474383881.0, u'isdir': True, u'ctime': 1474076736.0, u'isblk': False, u'xgrp': True, u'dev': 16777220, u'roth': True, u'isfifo': False, u'mode': u'0755', u'islnk': False}, u'changed': False, '_ansible_no_log': False, '_ansible_item_result': True, 'item': {u'name': u'google-chrome', u'install_path': u'/Applications/Google Chrome.app'}

It looks like the `Install casks` task should refer to the `item.item.name` instead of `item.name` with the item dict.

**Comment by ravenac95** [comment]
Good catch

**Comment by ravenac95** [comment]
Perhaps i should test better :P
